#!/bin/bash

# group-prs.sh <input-json-file>
# Replace <input-json-file> with the path to the JSON file generated by compute-stats.sh.

# Input JSON file (passed as a parameter)
INPUT_JSON="$1"

# Validate that the input JSON file exists and is readable
if [ ! -r "$INPUT_JSON" ]; then
  echo "Error: Input file '$INPUT_JSON' does not exist or is not readable" >&2
  exit 1
fi

# Validate JSON structure
if ! jq empty "$INPUT_JSON" 2>/dev/null; then
  echo "Error: Invalid JSON format in '$INPUT_JSON'" >&2
  exit 1
fi

# Group PRs by title and status
GROUPED_PRS=$(jq '
  group_by(.title) |
  map({
    title: .[0].title,
    merged: map(select(.state == "MERGED")) | length,
    open: map(select(.state == "OPEN")) | length,
    closed: map(select(.state == "CLOSED")) | length,
    prs: .
  })' "$INPUT_JSON")

# Output the grouped PRs to a new JSON file
OUTPUT_JSON="grouped_prs_$(basename "$INPUT_JSON")"
echo "$GROUPED_PRS" > "$OUTPUT_JSON"

echo "Grouped PRs have been saved to $OUTPUT_JSON"

# Activate the virtual environment (if it exists)
if [ -d "venv" ]; then
  source venv/bin/activate
else
  echo "Virtual environment not found. Please create it first."
  exit 1
fi

# Run the Python script to upload data to Google Sheets
python3 upload_to_sheets.py

# Deactivate the virtual environment (optional)
deactivate
