github:
  # These values should be set via environment variables or CLI parameters
  user: "updatecli[bot]"
  email: "updatecli@jenkins.io"
  owner: "jenkins-infra"
  repository: "alpha-omega-stats"
  token: "UPDATECLI_GITHUB_TOKEN"  # This should be set as an environment variable
  username: "updatecli"
  branch: "main"