name: Auto-merge Bot PRs

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]
    branches:
      - main

jobs:
  automerge:
    if: |
      github.event.pull_request.user.login == 'github-actions[bot]' &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      contains(github.event.pull_request.labels.*.name, 'automation')
    runs-on: ubuntu-latest
    steps:
      - name: Enable auto-merge for eligible PRs
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
