name: Weekly Top 250 Plugins CSV

on:
  schedule:
    - cron: '0 0 * * 1'  # Every Monday at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-top-plugins:
    runs-on: ubuntu-latest
    env:
      PLUGIN_CSV: top-250-plugins.csv
    steps:
      - uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Download plugins.json
        run: curl -L https://updates.jenkins.io/current/update-center.actual.json -o plugins.json

      - name: Generate top-250-plugins.csv
        run: bash get-most-popular-plugins.sh

      - name: Validate top-250-plugins.csv
        run: bash validate-top-plugins.sh

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet $PLUGIN_CSV; then
            echo "No changes detected."
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected."
            BRANCH="update-top-plugins-$(date +%Y%m%d%H%M%S)"
            echo "branch_name=$BRANCH" >> $GITHUB_OUTPUT
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create and push branch if changes detected
        if: steps.changes.outputs.changed == 'true'
        run: |
          git checkout -b "${{ steps.changes.outputs.branch_name }}"
          git add $PLUGIN_CSV
          git commit -m "Update top-250-plugins.csv"
          git push origin "${{ steps.changes.outputs.branch_name }}"

      - name: Create Pull Request
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ steps.changes.outputs.branch_name }}
          title: "[bot] Update top-250-plugins.csv"
          body: "Automated update of top-250-plugins.csv"
          labels: automation
