# This is a GitHub Actions workflow named "updatecli"
name: updatecli

on:
  # This workflow can be triggered manually via the GitHub Actions interface
  workflow_dispatch:

  # This workflow is scheduled to run once per week to avoid alert fatigue
  # Specifically, it runs every Monday at 8am UTC
  schedule:
    - cron: '0 8 * * 1'

  # This workflow is triggered on every push event to the repository
  push:

  # This workflow is triggered on every pull request event to the repository
  pull_request:

jobs:
  # This job is named "updatecli"
  updatecli:
    # This job runs on the latest version of Ubuntu
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository using the GitHub Actions checkout action
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Install Updatecli in the runner using the Updatecli GitHub Action
      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@v2.82.0

      # Step 3: Run Updatecli in Dry Run mode
      # The "diff" command of Updatecli is used with the specified config and values files
      # The GitHub token is passed as an environment variable for authentication
      - name: Run Updatecli in Dry Run mode
        run: updatecli diff --config ./updatecli/updatecli.d --values ./updatecli/values.github-action.yaml
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 4: Run Updatecli in Apply mode, but only if the current branch is 'main'
      # The "apply" command of Updatecli is used with the specified config and values files
      # The GitHub token is passed as an environment variable for authentication
      - name: Run Updatecli in Apply mode
        if: github.ref == 'refs/heads/main'
        run: updatecli apply --config ./updatecli/updatecli.d --values ./updatecli/values.github-action.yaml
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
